apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mbta2mqtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbta2mqtt
    app.kubernetes.io/part-of: mbta2mqtt
  name: mbta2mqtt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: mbta2mqtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mbta2mqtt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mattdm-tenant/mbta2mqtt/mbta2mqtt@sha256:5f45a332cd3027450bf411057ea80e11d8775fd59ff5fb50ebf06d727542439d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
