apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mbta2mqtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbta2mqtt
    app.kubernetes.io/part-of: mbta2mqtt
  name: mbta2mqtt
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: mbta2mqtt
status:
  loadBalancer: {}
